name: Build Doxygen and deploy to GitHub Pages
permissions:
    actions: read
    contents: write
    pages: write

on:
    push:
        branches:
        - Deploy-branch-Awsome-CSS

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        concurrency: ci-${{github.ref}}
        steps:          
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install Dependencies
              run: sudo apt-get install graphviz -y
              shell: bash

            # - name: Install Custom Doxygen Version 
            #   uses: AdarshRawat1/Install-Doxygen@v1.0
            #   with:
            #     version: '1.11.0'
            - name: Export Doxygen version in environment
              shell: bash
              run: |
                echo "DOXYGEN_VERSION=1.9.1" >> $GITHUB_ENV

            - name: "Installation"
              shell: bash
              run: |
                wget https://github.com/doxygen/doxygen/releases/download/Release_${DOXYGEN_VERSION//./_}/doxygen-${DOXYGEN_VERSION}.linux.bin.tar.gz
                tar xzvf doxygen-${DOXYGEN_VERSION}.linux.bin.tar.gz
                cd doxygen-${DOXYGEN_VERSION}
                sudo make install
                cd ..
                rm -rf doxygen-${DOXYGEN_VERSION}*             
            - name: Generate Doxygen Documentation
              run: |
                   cd docs/doxygen
                   doxygen doxygen.cfg
              shell: bash

            - name: Create .nojekyll
              run: |
                    cd docs/doxygen/build
                    touch html/.nojekyll
              shell: bash

            - name: Deploy to GitHub Pages
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                branch: gh-pages
                folder: docs/doxygen/build/html
